---
author:
  Sean Davis, MD/PhD
title: "The Hou*R* of Code"
subtitle: 'An overview of the *R* language in action'
date: '`r format(Sys.Date(),"%A, %B %d, %Y")`'
output: 
  ioslides_presentation:
    keep_md: true
---

# Introduction

## What is R?

- A software package
- A programming language
- A toolkit for developing statistical and analytical tools
- An extensive library of statistical and mathematical software and algorithms
- A scripting language
- ...

## Why R?

- R is cross-platform and runs on Windows, Mac, and Linux (as well as more obscure systems).
- R provides a vast number of useful statistical tools, many of which have been painstakingly tested.
- R produces publication-quality graphics in a variety of formats.
- R plays well with FORTRAN, C, and scripts in many languages.
- R scales, making it useful for small and large projects.  It is NOT Excel.
- R eschews the GUI.

> I can develop code for analysis on my Mac laptop.  I can then install the *same* code on our massive computer cluster and run it in parallel on 1000 samples, monitor the process, and then update a database with R when complete.

## Why not R?

- R cannot do everything.
- R is not always the ``best'' tool for the job.
- R will \textit{not hold your hand.
- The documentation can be opaque.
- R can drive you crazy (on a good day) or age you prematurely (on a bad one).
- Finding the right package to do the job you want to do can be challenging; worse, some contributed packages are unreliable.
- R eschews the GUI.

## R License and the Open Source Ideal

- R is free!
- Distributed under GNU license
    - You may download the source code.
    - You may modify the source code to your heart's content.
    - You may distribute the modified source code and even charge money for it, 
    - *but* you must distribute the modified source code under the original GNU license

### Take-home Message

This license means that R will always be available, will always be open source, and can grow organically without constraint.
